version: 0.{build}
image: Visual Studio 2017
platform: x86
configuration: Debug
build:
  verbosity: minimal

for:
-
  branches:
    only:
      - Releases
  configuration: Release

  artifacts:  
    - path: Warcraft Heroes Beyond Time.zip

  deploy:
  - provider: GitHub
    artifact: Warcraft Heroes Beyond Time.zip
    draft: false
    prerelease: false
    on:
      branch: Releases
      appveyor_repo_tag: true
