version: 0.{build}
image: Visual Studio 2017
platform: x86
configuration: Release
build:
  verbosity: minimal

for:
-
  branches:
    only:
      - releases
  configuration: Release

  after_build:
    - 7z a "Warcraft Heroes Beyond Time.zip" "%APPVEYOR_BUILD_FOLDER%/Warcraft Heroes Beyond Time/Game/*"
    - 7z a "Warcraft Heroes Beyond Time.zip" "%APPVEYOR_BUILD_FOLDER%/Warcraft Heroes Beyond Time/Release/Warcraft Heroes Beyond Time.exe"
    - 7z a "Warcraft Heroes Beyond Time.zip" "%APPVEYOR_BUILD_FOLDER%/docs/README.md"

  artifacts:  
    - path: "Warcraft Heroes Beyond Time.zip"

  deploy:
  - provider: GitHub
    release: Warcraft Heroes Beyond Time v$(appveyor_build_version)
    artifact: "Warcraft Heroes Beyond Time.zip"
    auth_token:
      secure: RmJh3KY08MINd/TWolIkLr04OXyj8QlMamglHUHHfHj1/ArjkWDbSoWNFd12JuA0
    draft: false
    prerelease: false
    on:
      branch: releases
      appveyor_repo_tag: true

  notifications:
      - provider: Email
        on_build_success: true
        on_build_failure: false
        on_build_status_changed: false
        to:
          - jony635molina@gmail.com
        subject: 'Success Warcraft Release {{buildVersion}}'
        message: "Good Job!"

      - provider: Slack
        auth_token:
          secure: CG/bUw6LmV4j4bsJnPQrmt8Fa50rKLnattAUz6bbY2iHnn8ESMoAyUpVZo0rMSiBbczkuYOm4OJf+wKWmQz5nq+yEVU8DWl49TgJ7zhTc=
        channel: '#notificaciones'
        template: "Success Release {{buildVersion}}! Good Job!"
        
-
  branches:
    only:
      - master
  notifications:    
      - provider: Email
        on_build_success: true
        on_build_failure: false
        on_build_status_changed: false
        to:
          - jony635molina@gmail.com
        subject: 'Success Warcraft Build {{buildVersion}}'
        message: "Good Job!"
